name: neural_trainer_onboarding
description: Neural trainer onboarding app demo.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logos/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/font/Rubik-Bold.ttf
          weight: 700
        - asset: assets/font/Rubik-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/font/Rubik-Medium.ttf
          weight: 500
        - asset: assets/font/Rubik-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/font/Rubik-Regular.ttf
          weight: 400
